### ISSUE TITLE
Unauthenticated SQL Injection

### ISSUE THREAD

**Issue by m-q-t** [bigprof-software/online-invoicing-system#3]
Hi team,

While reviewing the source code for this application, I've noticed there is the possibility of injecting user controlled SQL statements which would allow for complete compromise of the application.

**Note**: The proof of concept is demonstrated in the `Actual Exploitation` section.

**{Edit by repo author: details temporarily redacted till the issue is fixed within a few days}**

Lastly I just wanted to say thank you so much for releasing such awesome open source applications. I've had a lot of fun testing this application as the code is very well written and the application itself serves a realistic purpose. 

Please let me know if you have any questions regarding this issue.

Best regards,
\- mqt

**Comment by bigprof** [comment]
Thanks a lot for the detailed report. I've been able to reproduce this vulnerability and I'm working on a fix for it now. I've temporarily removed the details till a fix is made, then will restore the details once the fix is committed. You did a really impressive job that I rarely see in any vulnerability report. Thanks so much :)
