### ISSUE TITLE
CSRF -> Privilege Escalation

### ISSUE THREAD

**Issue by m-q-t** [bigprof-software/online-invoicing-system#4]
<redacted>

**Comment by bigprof** [comment]
@m-q-t I really admire the attention to detail you're demonstrating, and certainly all the effort you put into your reports. They are clear, concise and done with so much care. Unlike many thoughtless reports I receive that are simply automated pen-tests that are of no practical use.

Having said that, I'd really appreciate it if you stick to responsible disclosure, by sending your reports privately to my email address listed in our profile page. And then allowing a few days for us to investigate and make a fix. This prevents exposing our app users without prior warning. The way you're reporting now is a 0-day, and I really hate to see such effort being considered offensive because it was disclosed publicly like that without prior notification :/

I've added a security policy document to the repo that emphasizes the above points. I'd really appreciate it if you delete the issue above, and resend by email. I'll fix it as soon as possible, within a few days, then we can make it public and I'll certainly acknowledge your contribution in the release notes.

Thanks and I appreciate your understanding :)

**Comment by m-q-t** [comment]
Hi @bigprof,

Appreciate the quick reply and the kind words. My apologies if this caused any panic as it wasn't my intention. You're completely correct in the fact that this is would be considered a 0 day and as such I will report this issue and any future issues via email.

I'm unable to delete the Github issue itself, however I've redacted the content.

My apologies again for disclosing this publicly. With that being said, I'm looking forward to working with your team via responsible disclosure.

Best regards,
\- mqt

**Comment by bigprof** [comment]
@m-q-t This issue is now fixed. Thanks once more for the impressive work.

**Comment by m-q-t** [comment]
Happy to hear, appreciate the quick fix and looking forward to testing it soon ;) 

Best regards,
\- Maxim
